// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechSupportSystem.Data;

#nullable disable

namespace TechSupportSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425083948_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("TechSupportSystem.Models.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NoteId");

                    b.HasIndex("TicketId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            NoteId = 1,
                            Content = "Initial diagnostic started",
                            CreatedAt = new DateTime(2026, 1, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            TicketId = 1
                        },
                        new
                        {
                            NoteId = 2,
                            Content = "Checked printer queue, jobs stuck",
                            CreatedAt = new DateTime(2026, 1, 1, 2, 0, 0, 0, DateTimeKind.Utc),
                            TicketId = 1
                        },
                        new
                        {
                            NoteId = 3,
                            Content = "User reconfigured email account",
                            CreatedAt = new DateTime(2026, 1, 2, 1, 0, 0, 0, DateTimeKind.Utc),
                            TicketId = 2
                        },
                        new
                        {
                            NoteId = 4,
                            Content = "VPN logs show packet loss",
                            CreatedAt = new DateTime(2026, 1, 3, 1, 0, 0, 0, DateTimeKind.Utc),
                            TicketId = 3
                        });
                });

            modelBuilder.Entity("TechSupportSystem.Models.Technician", b =>
                {
                    b.Property<int>("TechnicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("TechnicianId");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            TechnicianId = 1,
                            Level = 2,
                            Name = "Alice"
                        },
                        new
                        {
                            TechnicianId = 2,
                            Level = 3,
                            Name = "Bob"
                        },
                        new
                        {
                            TechnicianId = 3,
                            Level = 1,
                            Name = "Charlie"
                        });
                });

            modelBuilder.Entity("TechSupportSystem.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("TicketId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Printer not working",
                            Priority = "High",
                            Status = "Open"
                        },
                        new
                        {
                            TicketId = 2,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Email not syncing on mobile",
                            Priority = "Medium",
                            Status = "Open"
                        },
                        new
                        {
                            TicketId = 3,
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "VPN connection dropping frequently",
                            Priority = "High",
                            Status = "In Progress"
                        });
                });

            modelBuilder.Entity("TechnicianTicket", b =>
                {
                    b.Property<int>("TechniciansTechnicianId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketsTicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TechniciansTechnicianId", "TicketsTicketId");

                    b.HasIndex("TicketsTicketId");

                    b.ToTable("TechnicianTicket");

                    b.HasData(
                        new
                        {
                            TechniciansTechnicianId = 1,
                            TicketsTicketId = 1
                        },
                        new
                        {
                            TechniciansTechnicianId = 2,
                            TicketsTicketId = 1
                        },
                        new
                        {
                            TechniciansTechnicianId = 2,
                            TicketsTicketId = 2
                        },
                        new
                        {
                            TechniciansTechnicianId = 1,
                            TicketsTicketId = 3
                        },
                        new
                        {
                            TechniciansTechnicianId = 3,
                            TicketsTicketId = 3
                        });
                });

            modelBuilder.Entity("TechSupportSystem.Models.Note", b =>
                {
                    b.HasOne("TechSupportSystem.Models.Ticket", "Ticket")
                        .WithMany("Notes")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TechnicianTicket", b =>
                {
                    b.HasOne("TechSupportSystem.Models.Technician", null)
                        .WithMany()
                        .HasForeignKey("TechniciansTechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechSupportSystem.Models.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketsTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechSupportSystem.Models.Ticket", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
